#!/system/bin/sh
#Code by @chamchamfy
mount -o rw,remount / 2> /dev/null; 
mkdir -p /sdcard/ur/bins 2> /dev/null; 
mkdir -p /sdcard/ur/bin 2> /dev/null; 
bint=/data/data/com.termux/files/usr/bin 
[ -e /system/bin -a -w /system/bin ] && bin=/system/bin || bin=/bin; 
bins=/sdcard/ur/bins 
binu=/sdcard/ur/bin
echo -n " + Tải dữ liệu mới (c/k): "; read k; 
if [ "$k" = "c" ]; then echo " + Đang cập nhật..."; 
[ ! -f /sdcard/ur/bin.so ] && curl -L# https://sourceforge.net/projects/chamchamfy/files/Tools/bin.so -o /sdcard/ur/bin.so 2> /dev/null 
[ -f /sdcard/ur/bin.so ] && tar -xJf /sdcard/ur/bin.so -C /sdcard/ur 2> /dev/null 
else echo " + Bỏ qua!"; 
fi 
cp -af $binu/* $bint 2> /dev/null 
cp -af $bins/* $bint 2> /dev/null 
chmod +x $bint/* 2> /dev/null 
cp -af $binu/* $bin 2> /dev/null 
cp -af $bins/* $bin 2> /dev/null 
chmod +x /$bin/* 2> /dev/null 
exit; 