name: 'CHAY'
on: 

  workflow_dispatch:
jobs:
  build:
    name: 'Xem quá trình...'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          # Run Rebuild 
          bash .github/Chay.sh
      - uses: actions/upload-artifact@v3
        with:
          name: overlay.zip
          path: .github/signed/*
          retention-days: 3
