name: 'CHAY'
on: 

  workflow_dispatch:
    inputs:
      AL:
        description: 'Thêm âm lịch'
        required: true
        default: '1'
        type: choice
        options:
          - '1'
          - '0'
jobs:
  build:
    name: 'Xem quá trình...'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          # Run Rebuild 
          chmod 777 .github/* 2>/dev/null 
          export NG="$(date +"%y%m%d")"
          echo "PB=$NG" >> $GITHUB_ENV
          echo "AL=$AL" >> $GITHUB_ENV
          .github/Reo
      - uses: actions/upload-artifact@v3
        with:
          name: overlay.zip
          path: signed/*
          retention-days: 3
      - name: 'Overlay'
        uses: softprops/action-gh-release@v1
        with:
          name: Overlay_V1.${{ env.AL }}.${{ env.PB }}
          tag_name: Overlay_V1.${{ env.AL }}.${{ env.PB }}
          files: OV/*
          prerelease: true
      - name: 'Flash Overlay'
        uses: softprops/action-gh-release@v1
        with:
          name: VH_XIAOMI_TWRP_V1.${{ env.AL }}.${{ env.PB }}
          tag_name: VH_XIAOMI_TWRP_V1.${{ env.AL }}.${{ env.PB }}
          files: UP/*
          prerelease: true
