
name: 'CHAY'
on: 
  workflow_dispatch:
jobs:
  
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu:20.04"
            pkgs: "clang-11 libstdc++-10-dev"
            env1: "CC=clang-11 CXX=clang++-11"

    container:
      image: ${{ matrix.os }}
      options: --security-opt seccomp=unconfined

    steps:
      - name: build
        run: |
          bash /Chay.sh
      - name: upload   
        uses: actions/upload-artifact@v3
        with:
          name: overlay.zip
          path: signed
          retention-days: 3
