name: 'CHAY'
on: 

  workflow_dispatch:
jobs:
  build:
    name: 'Xem quá trình...'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          # Run Rebuild 
          chmod 777 .github/* 2>/dev/null 
          #bash .github/Chay.sh
          .github/Reo
      - uses: actions/upload-artifact@v3
        with:
          name: overlay.zip
          path: .github/signed/*
          retention-days: 3
